blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from accounts.views import (login_view, register_view, logout_view)


urlpatterns = [
    path('contact/', include("contact.urls")),
    path('admin/', admin.site.urls),
    path('comments/', include("comments.urls")),
    
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include("posts.urls")),
    #path('posts/$', "<appname>.views.<function_name>"),
    path('robots\.txt', TemplateView.as_view(template_name='src/robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	PostLikeToggle,
	PostLikeAPIToggle,
	)
app_name ='posts'

urlpatterns = [
	re_path(r'^$', post_list, name='list'),
    re_path(r'^create/$', post_create),
    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	re_path(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
	re_path(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    re_path(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #re_path(r'^posts/$', "<appname>.views.<function_name>"),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    # def get_api_url(self):
    #     return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["-timestamp", "-updated"]

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=True))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

templates/blog/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Team JELOBLIS">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="keywords" content="Entertainment blog, education news, scholarships in nigeria, jamb, waec, neco, post utme, nigeria lifestyle, nigeria politics, politics, lifestyle, jamb results, neco results, waec results, nigeria universities cut off mark," />
    
    <title>BLOG8 {% block head_title %}{% endblock head_title %}</title>

    <!--Main Cascading Style Sheet-->
    <link rel='stylesheet' href='{% static "css/base.css" %}' />
    
      
    <!--[if lt IE 9 ]>
        <script type="text/javascript" src="https://codropspz-tympanus.netdna-ssl.com/codrops/wp-content/themes/codropstheme03/js/css3-mediaqueries.js"></script>
        <link rel="stylesheet" href="https://codropspz-tympanus.netdna-ssl.com/codrops/wp-content/themes/codropstheme03/css/ie.css"/>
    <![endif]-->
    <!--[if lt IE 8 ]>
        <script type="text/javascript" src="https://codropspz-tympanus.netdna-ssl.com/codrops/wp-content/themes/codropstheme03/js/iconfonts.js"></script>
    <![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href='{% static "css/ie9.css" %}' /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href='{% static "css/ie8.css" %}' /><![endif]-->
    <meta name="description" content="Tech News, Tutorials and Reviews."/>

    {% block head_extra %} {% endblock head_extra %}
</head>
<body>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    
    {% if messages %}
        <div class='messages'>

        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
        {% endfor %}
        </ul>

        </div>
    {% endif %}
    

    <div id="wrapper">
        
        <!-- Header -->
        <header id="header">
            <h1><a href='{% url "posts:list" %}'>BLOG8</a></h1>
            
            <nav class="main">
                <ul>
                    <li class="search">
                        <a class="fa-search" href="#search">Search</a>
                        <form id="search" method="get" action="">
                            <input type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                        </form>
                    </li>
                    <li class="menu">
                        <a class="fa-bars" href="#menu">Menu</a>
                    </li>
                </ul>
            </nav>
        </header>

        <!--Side Navigation With Login/Register Form-->
        {% include "sidenav.html" %}

        <!--Main Content-->
        <div id="main">
            {% block content %}{% endblock content %}
        </div>

        <!-- Sidebar -->
        <section id="sidebar">

            <!-- Intro -->
                <section id="intro">
                    <a href="#" class="logo"><img src="images/logo.jpg" alt="" /></a>
                    <header>
                        <h2>BLOG 8</h2>
                        <p>Django News, Updates and How-To</a></p>
                    </header>
                </section>

            {% block minipost %}
            
            {% endblock minipost %}

            {% block postlist %}
            
            {% endblock postlist %}

            <!-- About -->
                <section class="blurb">
                    <h2>About</h2>
                    <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
                    <ul class="actions">
                        <li><a href="#" class="button">Learn More</a></li>
                    </ul>
                </section>

            <!-- Footer -->
                <section id="footer">
                    <ul class="icons">
                        <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                        <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                        <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                        <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                    </ul>
                    <p class="copyright">&copy; Untitled. Crafted: <a href="http://designscrazed.org/">HTML5</a>.</p>
                </section>

        </section>

    </div><!--end wrapper-->

    <!-- Latest compiled and minified JavaScript -->
    <script src='{% static "js/jquery.min.js" %}'></script>
    <!--[if lte IE 8]><script src="{% static "js/respond.min.js" %}"></script><![endif]-->
    <script src='{% static "js/skel.min.js" %}'></script>
    <script src='{% static "js/util.js" %}'></script>
    <script src='{% static "js/base.js" %}'></script>

    <script>
        $(document).ready(function(){
             function updateText(btn, newCount){
             btn.text(newCount)
         }
         $(".like-btn").click(function(e){
           e.preventDefault()
           var this_ = $(this)
           var likeUrl = this_.attr("data-href")
           var likeCount = parseInt(this_.attr("data-likes")) | 0
           var addLike = likeCount + 1
           var removeLike = likeCount - 1
           if (likeUrl){
              $.ajax({
               url: likeUrl,
               method: "GET",
               data: {},
               success: function(data){
                 console.log(data)
                 var newLikes;
                 if (data.liked){
                     updateText(this_, addLike,)
                 } else {
                     updateText(this_, removeLike,)
                     // remove one like
                 }
               }, error: function(error){
                 console.log(error)
                 console.log("error")
               }
             })
           }
          
         })
     })
    </script>

    <script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
                var content = $(this).text()
                var markedContent = marked(content)
                $(this).html(markedContent)
        })
        $(".post-detail-item img").each(function(){
                $(this).addClass("img-responsive");
        })

        

        var contentInput = $("#id_content");

        function setContent(value){
            var markedContent = marked(value)
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function(){
                $(this).addClass("img-responsive")
            })
        }
        setContent(contentInput.val())

        contentInput.keyup(function(){
            var newContent = $(this).val()
            setContent(newContent)
        })

        var titleInput = $("#id_title");
        


        function setTitle(value) {
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function(){
            var newContent = $(this).val()
            setTitle(newContent)
        })

        $(".comment-reply-btn").click(function(event){
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })


        // preview-title
        // preview-content

    })

    </script>

    </body>
</html>