blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from accounts.views import (login_view, register_view, logout_view)


urlpatterns = [
    path('contact/', include("contact.urls")),
    path('admin/', admin.site.urls),
    path('comments/', include("comments.urls")),
    
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include("posts.urls")),
    #path('posts/$', "<appname>.views.<function_name>"),
    path('robots\.txt', TemplateView.as_view(template_name='src/robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.conf.urls import include, url
from django.urls import path, re_path
from django.contrib import admin

from .views import (
    contact,
    thanks
    )

app_name='contact'

urlpatterns = [
    path('', contact, name='contact'),
    path('thanks/', thanks, name='thanks'),
]

posts/urls.py
from django.urls import path, re_path
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	PostLikeToggle,
	PostLikeAPIToggle,
	)
app_name ='posts'

urlpatterns = [
	re_path(r'^$', post_list, name='list'),
    re_path(r'^create/$', post_create),
    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
	re_path(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
	re_path(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    re_path(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #re_path(r'^posts/$', "<appname>.views.<function_name>"),
]

contact/models.py
from django.db import models

# Create your models here.

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    # def get_api_url(self):
    #     return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["-timestamp", "-updated"]

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True, label="Name")
    contact_email = forms.EmailField(required=True, label="Email")
    content = forms.CharField(
        required=True,
        widget=forms.Textarea,
        label="Message"
    )

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=True))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

contact/views.py
from django.core.mail import BadHeaderError, EmailMessage
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            contact_name = form.cleaned_data['contact_name']
            contact_email = form.cleaned_data['contact_email']
            content = form.cleaned_data['content']
            try:
                email = EmailMessage(contact_name,
                                    content,
                                    contact_email,
                                    ['jeremiahedavid@gmail.com'], #change to your email
                                     reply_to=[contact_email],
                                   )
                email.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/')
    return render(request, 'contact.html', {'form': form})


def thanks(request):
    return redirect ('thanks.html', )

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import RedirectView

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
		
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		# message success
		messages.success(request, "Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated:
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	comments = instance.comments
	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		"comment_form":form,
	}
	return render(request, "post_detail.html", context)


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get("slug")
        print(slug)
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions

class PostLikeAPIToggle(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, slug=None, format=None):
        # slug = self.kwargs.get("slug")
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            "updated": updated,
            "liked": liked
        }
        return Response(data)



def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)





def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "post_form.html", context)



def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

templates/comment_thread.html
{% extends "blog/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{{ object }}



<div>
        
          <p>{{ comment.content }}</p>
          <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'>Delete</a> {% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-default'>
            </form>
            {% else %}
            <p>You must login to comment </p>
            {% endif %}
        </div>

        <hr/>
</div>


{% endblock content %}

templates/confirm_delete.html
{% extends "blog/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
<div class="post">
    <h1>Confirm Delete</h1>
    <form method="POST" action="."> {% csrf_token %}
        <p>A re you sure you want to delete: "{{ object.content }}"?</p>
        
        <input type='submit' value='Confirm' class='btn btn-warning'>
        <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
    </form>

    <hr/>
</div>
{% endblock content %}

templates/contact.html
{% extends "blog/base.html" %}

{% load widget_tweaks %}

{% block content %}
    <div class="post">
        <header>
            <div class="title">
                <h2>GET INTOUCH!</h2>
            </div>
        </header>
        

        <form class="form-horizontal" role="form" action="." method="post">
        {% csrf_token %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="col-md-6">
                            {{ field|attr:"class:form-control" }}
                            <span class="help-block">
                                {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="col-md-6">
                            {{ field|attr:"class:form-control" }}
                            {% if field.help_text %}
                                <p class="help-block"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="form-group">
                <div class="col-md-offset-3 col-md-6">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>

        </form>

    </div>
    
    {% endblock content %}

templates/error_404.html
{% extends "blog/base.html" %}
{% load staticfiles %}


{% block content %}
<div class="agile">
    <div class="agileits_main_grid">
        <div class="agileits_main_grid_left">
            
            <div class="w3l">
                <div class="text">
                    <h1>BLOG*</h1>
                    <h3>404</h3>
                    <h2>SORRY THE PAGE YOU ARE LOOKING FOR DOES NOT EXIST.</h2>	
                    <div class="wthree">
                        <div class="back">
                            <a href='{% url "posts:list" %}'>RETURN HOME</a>
                        </div>
                        <div class="social-icons w3agile">
                            <ul>
                                <li><a href="#" class="fa-facebook"></a></li>
                                <li><a href="#" class="fa-twitter"></a></li>
                                <li><a href="#" class="fa-googleplus"></a></li>
                                <div class="clear"></div>
                            </ul>	
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="w3ls_form">
                    
                    <h5>STAY TUNED AND DON'T FORGET SIGN UP FOR LATEST UPDATES</h5>
                        <form action="#" method="post">
                            <input type="text" name="Keyword" placeholder="Enter your email here..." required="">
                            <input type="submit" value="Subscribe">
                            <div class="clear"></div>
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="agileits_main_grid_right">
            <div class="menu">
                <span class="fa-menu"><a href="#"></a></span>	
                    <ul class="nav1">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Gallery</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul> 	
                    <!-- script-for-menu -->
                     <script>
                       $( "span.menu-icon" ).click(function() {
                         $( "ul.nav1" ).slideToggle( 300, function() {
                         // Animation complete.
                          });
                         });
                    </script>
                    <!-- /script-for-menu -->
            </div>
        </div>
        <div class="clear"> </div>
    </div>
</div>
{% endblock content %}

templates/form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='post'>
    <header>
        <div class="title">
            <h2>{{ title }}</h2>
        </div>
    </header>

    <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='btn btn-default' value='{{ title }}' />
    </form>
</div>
{% endblock content %}

templates/messages_display.html
{% extends "blog/base.html" %}
{% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/post_detail.html
{% extends "blog/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

 {% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
  {% endblock %}


{% block content %}
<!-- Post -->
<div class="post">
    <header>
        <div class="title">
            <h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.publish }}</small></h1>
            {% if instance.draft %}
            <h3>Staff only: Draft</h3>
            {% endif %} 
            {% if instance.publish > today %}
            <h3>Staff Only: Future Post</h3>
            {% endif %}
            <p>BLOG8 POST</p>
        </div>
        <div class="meta">
            <p class="published">{{ publish }}</p>
            {% if instance.draft %}<h3>Staff only: Draft</h3>{% endif %} 
            {% if instance.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
            {% if instance.publish > today %}
            <time class="published" datetime="">{{ publish }}</time>
            {% endif %}
            {% if instance.user.get_full_name %}<p>Author: {{ instance.user.get_full_name }}</p>{% endif %}
            <p>Read time: {% if instance.read_time <= 1 %} > 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>
        </div>
    </header>
    {% if instance.image %}
    <a href="#" class="image featured"><img src='{{ instance.image.url }}' alt="" /></a>
    {% endif %}


    <div class='post-detail-item'>{{ instance.get_markdown }}</div>
    <footer>
        <ul class="actions">
            <li><a href='{% url "posts:list" %}' class="button big">Return To Posts</a></li>
        </ul>
        <ul class="stats">
            <li><a data-href='{{ instance.get_api_like_url }}' data-likes='{{ instance.likes.count }}' href='{{ instance.get_like_url }}' class="icon fa-heart like-btn active" >{{ instance.likes.count }}</a></li>
            <li><a class="icon fa-share fb-like" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" data-layout='button-count' data-action="like" data-show-faces="true" data-share="true" ></a></li>
        </ul>
    </footer>
    <div class="comment">
        <p class='lead'>Comments</p>
        {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
            {{ comment_form|crispy }}
            <input type='submit' value='Post comment' class='btn btn-default'>
        </form>
        {% else %}
        <p>You must login to comment </p>
        {% endif %}
        <hr/>
        {% for comment in comments %}

        <blockquote>
            <p>{{ comment.content }}</p>
            <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> | <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>
            <div class='comment-reply'>
                {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
                {% endfor %}
                {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ comment_form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-default'>
            </form>
            {% else %}
        <p>You must login to comment </p>
        {% endif %}
        </div>

        </blockquote>

        <hr/>
        {% endfor %}
    </div>
</div>


<!-- <p>
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>

<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
Twitter
</a>

<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>


<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
Linkedin
</a>

<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}.">Reddit</a>

</p> -->
{% endblock content %}

templates/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}
{% endblock head_extra %}



{% block content %}
<div class='post'>
    <header>
        <div class="title">
            <h2>CREATE POST</h2>
        </div>
        <div class='content-preview'>
            <h3 id='preview-title'></h3>
            <p id='preview-content'></p>
        </div>
    </header>

    <div class='published'>
    <h1>POST CREATE FORM</h1>
    <hr/>

        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
        {{ form|crispy }}
        <input type='submit' class='button big fit' value='Create Post' />
        </form>
    </div>
</div>
{% endblock content %}

templates/sidebar.html
<!-- Sidebar -->
<section id="sidebar">

        <!-- Intro -->
            <section id="intro">
                <a href="#" class="logo"><img src="images/logo.jpg" alt="" /></a>
                <header>
                    <h2>BLOG 8</h2>
                    <p>Django News, Updates and How-To</a></p>
                </header>
            </section>

        {% block minipost %}
          
        {% endblock minipost %}

        {% block postlist %}
          
        {% endblock postlist %}

        <!-- About -->
            <section class="blurb">
                <h2>About</h2>
                <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
            </section>

        <!-- Footer -->
            <section id="footer">
                <ul class="icons">
                    <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                    <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                    <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                    <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                    <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
                </ul>
                <p class="copyright">&copy; Untitled. Crafted: <a href="http://designscrazed.org/">HTML5</a>.</p>
            </section>

    </section>

templates/sidenav.html
<!-- Menu -->
<section id="menu">

    <!-- Search -->
        <section>
            <form id="search" method="get" action="">
                <input type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
            </form>
        </section>

    <!-- Links -->
        <section>
            <ul class="links">
                <li><a href='{% url "posts:list" %}'>Home</a></li>
                <li><a href='{% url "contact:contact" %}'>Contact</a></li>
                {% block post_detail_link %}
                {% endblock %}
            </ul>
        </section>

    <!-- Actions -->
        <section>
            <ul class="actions vertical">
                {% if not request.user.is_authenticated %}
                <li class='button big fit'><a href='{% url "register" %}'>Register</a></li>
                <li class='button big fit'><a href='{% url "login" %}'>Login</a></li>
                {% else %}
                <li class='button big fit'><a href='{% url "logout" %}'>Logout</a></li>
                {% endif %}
            </ul>
        </section>

</section>

templates/test_callable_template_name.html
{% extends "blog/base.html" %}
Callable template_name used.

templates/thanks.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <h2>Success.</h2>
            <p>Thank you for getting in touch with us. <br>Your email has been recieved.</p>
        </div>
    </div>

</div>
{% endblock content %}